// <auto-generated />
using System;
using LibraryManagementBE.Repositories.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementBE.Migrations
{
    [DbContext(typeof(LibraryManagementDBContext))]
    partial class LibraryManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("077aaabb-ac69-4ab5-abe5-902dd5120fd9"),
                            ConcurrencyStamp = "31BF5413-8303-4E21-8D3A-10099FCA95FE",
                            Description = "Normal user",
                            Name = "NormalUser",
                            NormalizedName = "NORMALUSER"
                        },
                        new
                        {
                            Id = new Guid("eb994f87-ed00-477e-ab20-d66214de73cc"),
                            ConcurrencyStamp = "94BD65EE-DE64-4476-91AA-6258155DE018",
                            Description = "Act like Admin",
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        });
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1725b63b-f707-4b49-4ed2-08da06f835d7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79c962b7-4035-4016-bb71-f8a69e2deda3",
                            Dob = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nghia@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Le Trung Nghia",
                            Gender = 0,
                            IsDisabled = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NGHIA@GMAIL.COM",
                            NormalizedUserName = "NGHIALT",
                            PasswordHash = "AQAAAAEAACcQAAAAEIlZvLNbRbavKqtei6MSGTYZmh3s0juNAmlKvOXMQ0DP+YDBmpCN9ryMHOFh3hlbAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QXZYXIFQIFFM7TYFWNTSFT32V2J2Y7HM",
                            TwoFactorEnabled = false,
                            Type = 0,
                            UserName = "nghialt"
                        },
                        new
                        {
                            Id = new Guid("7f9f0ea3-a755-4d38-4ed1-08da06f835d7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65525777-0cc0-4364-8598-cdf93f0d5b14",
                            Dob = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dai@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Pham Ngoc Dai",
                            Gender = 0,
                            IsDisabled = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DAI@GMAIL.COM",
                            NormalizedUserName = "DAIPN",
                            PasswordHash = "AQAAAAEAACcQAAAAELvSL0FZEmF+U1eOPOPxZmlypBIxliBJCcynTzFGQmVd6FhiyAG9m56lFv6MNH4lNQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ST4X4QYRAABOJUBI2OA2F6CSNATJF7WB",
                            TwoFactorEnabled = false,
                            Type = 1,
                            UserName = "daipn"
                        });
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookBorrowingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RequestedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResponseById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.HasIndex("ResponseById");

                    b.ToTable("BookBorrowingRequest");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9ea1f61-6658-415d-883a-abf3a31599d5"),
                            RequestedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9569),
                            RequestedById = new Guid("7f9f0ea3-a755-4d38-4ed1-08da06f835d7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5ce6d93a-1c3e-47dc-ab74-fb401029a715"),
                            RequestedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9572),
                            RequestedById = new Guid("7f9f0ea3-a755-4d38-4ed1-08da06f835d7"),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("eb73d5bd-c73f-448c-b6ca-f1c8e32f6443"),
                            RequestedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9574),
                            RequestedById = new Guid("7f9f0ea3-a755-4d38-4ed1-08da06f835d7"),
                            Status = 2
                        });
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookBorrowingRequestDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DetailOfRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("DetailOfRequestId");

                    b.ToTable("BookBorrowingRequestDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bda7792a-225f-4847-8b06-a1adf5557070"),
                            BookId = new Guid("1119ea52-5703-48e3-9917-76bb49612653"),
                            BookName = "Mukushou Tensei",
                            DetailOfRequestId = new Guid("c9ea1f61-6658-415d-883a-abf3a31599d5")
                        },
                        new
                        {
                            Id = new Guid("34995d6c-9a2f-43ee-b741-9c37442d6d0a"),
                            BookId = new Guid("bffb1013-98ef-4d79-a040-7b0443a32dd2"),
                            BookName = "Tsuki ga Michibiku Isekai Douchuu",
                            DetailOfRequestId = new Guid("5ce6d93a-1c3e-47dc-ab74-fb401029a715")
                        },
                        new
                        {
                            Id = new Guid("f47c6a96-3789-437d-bd46-b683f3321ba5"),
                            BookId = new Guid("f6029ede-ecbe-47e0-84ed-9e94cdcbc2b5"),
                            BookName = "Eighty Six",
                            DetailOfRequestId = new Guid("eb73d5bd-c73f-448c-b6ca-f1c8e32f6443")
                        });
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6029ede-ecbe-47e0-84ed-9e94cdcbc2b5"),
                            CategoryId = new Guid("741d9d50-8d50-498d-a73a-0e5074aca3c6"),
                            CoverSrc = "https://static.wikia.nocookie.net/86-eighty-six/images/4/4c/Light_Novel_Volume_7_Cover.jpg",
                            Description = "The Republic of San Magnolia was attacked by its neighboring neighbor. It's an empire. In addition to the 85 counties of the Republic there is also \"the 86th district that does not exist\", where the elite young men and women continue to fight. Shin directs the combat of young suicide bombers, while Lena is the manager of a detachment of \"caretakers\" from the far rear. This story is about the tragic war between the two main characters above.",
                            Name = "Eighty Six",
                            PublishedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9546)
                        },
                        new
                        {
                            Id = new Guid("53884e6a-7bf5-4f62-87ad-f02bff3274ca"),
                            CategoryId = new Guid("4a3eda74-216c-4a99-9f97-8866250f15e6"),
                            CoverSrc = "https://static.wikia.nocookie.net/guiltycrown/images/f/fb/Guilty_Crown_poster.jpg",
                            Description = "In the near future, a meteorite carrying a strange virus (Apocalypse Virus) falls on Japan, leading to a biological disaster with a nationwide scale. And to help Japan, an international organization called GHQ came to the rescue. However, what Japan has to trade in return is independence. Ten years later (2039), a high school student named Ouma Shuu - who has a special power awakened by the Apocalypse Virus - coincidentally meets a girl named Yuzuriha Inori who is being hunted by GHQ. Since then, his life has been caught up in a series of unsolved mysteries",
                            Name = "Guilty Crown",
                            PublishedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9551)
                        },
                        new
                        {
                            Id = new Guid("1119ea52-5703-48e3-9917-76bb49612653"),
                            CategoryId = new Guid("4a3eda74-216c-4a99-9f97-8866250f15e6"),
                            CoverSrc = "https://static.wikia.nocookie.net/mushokutensei/images/5/5f/LN_Vol_25_JP.jpg",
                            Description = "The story is about an unemployed otaku who ends his life at the age of 34 due to being hit by a truck. What is surprising is that he finds himself reincarnated in the form of a newborn baby, living in a strange world full of magic and swordsmanship.\nHis new name is Rudeus Grayrat, but he still remembers his previous life. The story revolves around life from childhood to adulthood in a wonderful but dangerous world",
                            Name = "Mukushou Tensei",
                            PublishedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9553)
                        },
                        new
                        {
                            Id = new Guid("bffb1013-98ef-4d79-a040-7b0443a32dd2"),
                            CategoryId = new Guid("5070844a-2416-4101-bbef-c82f18923b37"),
                            CoverSrc = "https://s199.imacdn.com/tt24/2021/04/09/cd3319db9a8fbc65_784a78034e63d855_3031741617979942845957.jpg",
                            Description = "Makoto Misumi is just an ordinary high school student who lives an ordinary life, but is suddenly summoned to another world to become a \"hero\". However, the goddess of that world insulted him for being different and stripped him of his title of \"hero\", before banishing him to the wilderness at the edge of the world. As he roamed the wilderness, Makoto encountered dragons, spiders, orcs, dwarves, and all sorts of non-human tribes. Because Makoto came from another world, he was able to unleash magical powers and combat skills beyond imagination. But how will he handle when he meets many different creatures and survives in a new environment?",
                            Name = "Tsuki ga Michibiku Isekai Douchuu",
                            PublishedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9556)
                        });
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoryEntity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a3eda74-216c-4a99-9f97-8866250f15e6"),
                            CategoryName = "Romance",
                            CreatedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9515)
                        },
                        new
                        {
                            Id = new Guid("5070844a-2416-4101-bbef-c82f18923b37"),
                            CategoryName = "Isekai",
                            CreatedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9532)
                        },
                        new
                        {
                            Id = new Guid("741d9d50-8d50-498d-a73a-0e5074aca3c6"),
                            CategoryName = "Mecha",
                            CreatedAt = new DateTime(2022, 3, 23, 13, 51, 47, 235, DateTimeKind.Local).AddTicks(9533)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7f9f0ea3-a755-4d38-4ed1-08da06f835d7"),
                            RoleId = new Guid("077aaabb-ac69-4ab5-abe5-902dd5120fd9")
                        },
                        new
                        {
                            UserId = new Guid("1725b63b-f707-4b49-4ed2-08da06f835d7"),
                            RoleId = new Guid("eb994f87-ed00-477e-ab20-d66214de73cc")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookBorrowingRequest", b =>
                {
                    b.HasOne("LibraryManagementBE.Repositories.Entities.AppUser", "RequestedBy")
                        .WithMany("OwnRequested")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LibraryManagementBE.Repositories.Entities.AppUser", "ResponseBy")
                        .WithMany()
                        .HasForeignKey("ResponseById");

                    b.Navigation("RequestedBy");

                    b.Navigation("ResponseBy");
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookBorrowingRequestDetails", b =>
                {
                    b.HasOne("LibraryManagementBE.Repositories.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("LibraryManagementBE.Repositories.Entities.BookBorrowingRequest", "DetailOfRequest")
                        .WithMany("BooksRequested")
                        .HasForeignKey("DetailOfRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Book");

                    b.Navigation("DetailOfRequest");
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookEntity", b =>
                {
                    b.HasOne("LibraryManagementBE.Repositories.Entities.CategoryEntity", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.AppUser", b =>
                {
                    b.Navigation("OwnRequested");
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.BookBorrowingRequest", b =>
                {
                    b.Navigation("BooksRequested");
                });

            modelBuilder.Entity("LibraryManagementBE.Repositories.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
