// <auto-generated />
using System;
using EFCore_Ex2.Repositories.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_Ex2.Migrations
{
    [DbContext(typeof(ProductStoreDBContext))]
    partial class ProductStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore_Ex2.Repositories.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryEntity");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("df44bc42-6785-459b-8185-4d7f7c16b544"),
                            CategoryName = "Laptop"
                        });
                });

            modelBuilder.Entity("EFCore_Ex2.Repositories.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductEntity");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("614d1d14-5100-4e79-ba17-e0d6db051de8"),
                            CategoryId = new Guid("df44bc42-6785-459b-8185-4d7f7c16b544"),
                            Manufacture = "Dell",
                            ProductName = "Alienware X17"
                        },
                        new
                        {
                            ProductId = new Guid("c6fd585d-2227-43d8-b1a2-e5260eeb58ad"),
                            CategoryId = new Guid("df44bc42-6785-459b-8185-4d7f7c16b544"),
                            Manufacture = "Dell",
                            ProductName = "Alienware 15R6"
                        },
                        new
                        {
                            ProductId = new Guid("dd07a59f-e8ef-459e-8a17-ffd43476a9b8"),
                            CategoryId = new Guid("df44bc42-6785-459b-8185-4d7f7c16b544"),
                            Manufacture = "MSI",
                            ProductName = "MSI modern 14 B11"
                        });
                });

            modelBuilder.Entity("EFCore_Ex2.Repositories.Entities.ProductEntity", b =>
                {
                    b.HasOne("EFCore_Ex2.Repositories.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EFCore_Ex2.Repositories.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
